project:
  type: website
  output-dir: docs # For pages publishing

# Top navbar
website:
  title: "R Programming Course"
  navbar:
    left:
      - href: ./pages/index.Rmd
        text: Home
      - href: ./pages/prog_base.Rmd
        text: Basics
      - href: ./pages/r_paradigms.Rmd
        text: R
      - href: ./pages/statistics.Rmd
        text: Statistics  
      - href: ./pages/r_genomics.Rmd
        text: Genomics
    right: 
      - icon: github
        href: https://github.com/mtoninel
      - icon: twitter
        href: https://twitter.com/toninells
  page-footer: "Copyright 2023, Mattia Toninelli"

# Themes, can be changed with .css files and .scss 
format:
  html:
    theme: 
      - yeti
      - sass_styling.scss
    css: styles.css
    toc: true
    toc_float: true
    toc_collapsed: true

# Code theme
highlight-style: ayu