---
author: "Mattia Toninelli"
date: "06/02/23"
output: html_document
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center', warning = FALSE, message = FALSE)
```

# Introduction
The course will give an overview of R as an instrument for programming and efficient scripting, with a twist on using it to analyze biologically relevant data.
It will start with the basics and then develop into an exploration of ways to improve code performance and structure.
All of the materials from the lectures can be found [here](https://www.ceredalab.com/SPC/index.html), with relevant information related to the authors as well.

The course, which lasted one week, has been taught by Dr. _U. Pozzoli_, Dr. _F. Iannelli_ and Dr. _M. Cereda_ at [IEO](https://www.research.ieo.it/) in Milan.

The statistics page instead contains notes from a separate couse taught by Dr. _N. Pesenti_ at [INGM](https://ingm.org/).

All the material from the course is either mine or provided by the instructors. All of the code present within this site was developed and is readily implementable in [RStudio](https://posit.co/) using [RMarkdown](https://rmarkdown.rstudio.com/).
